
var YaneuraOu = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(YaneuraOu) {
  YaneuraOu = YaneuraOu || {};


function e(){l.buffer!=m&&q(l.buffer);return aa}function ba(){l.buffer!=m&&q(l.buffer);return ca}function y(){l.buffer!=m&&q(l.buffer);return da}function z(){l.buffer!=m&&q(l.buffer);return ea}function fa(){l.buffer!=m&&q(l.buffer);return ha}null;var A;A||(A=typeof YaneuraOu !== 'undefined' ? YaneuraOu : {});var ia,ja;A.ready=new Promise(function(a,b){ia=a;ja=b});A.Pa||(A.Pa=0);A.Pa++;
(function(a){function b(n,v,p){var r=new XMLHttpRequest;r.open("GET",n,!0);r.responseType="arraybuffer";r.onprogress=function(w){var h=v;w.total&&(h=w.total);if(w.loaded){r.ja?A.wa[n].loaded=w.loaded:(r.ja=!0,A.wa||(A.wa={}),A.wa[n]={loaded:w.loaded,total:h});var t=h=w=0,x;for(x in A.wa){var C=A.wa[x];w+=C.total;h+=C.loaded;t++}w=Math.ceil(w*A.Pa/t);A.setStatus&&A.setStatus("Downloading data... ("+h+"/"+w+")")}else!A.wa&&A.setStatus&&A.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
n);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(n){console.error("package error:",n)}function d(){function n(w,h,t){this.start=w;this.end=h;this.audio=t}function v(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);n.prototype.xb=w;w=a.files;for(var h=
0;h<w.length;++h)n.prototype.ja[w[h].filename].onload();A.removeRunDependency("datafile_yaneuraou.data")}A.FS_createPath("/","eval",!0,!0);n.prototype={ja:{},open:function(w,h){this.name=h;this.ja[h]=this;A.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Qa(this.xb.subarray(this.start,this.end))},Qa:function(w){A.FS_createDataFile(this.name,null,w,!0,!0,!0);A.removeRunDependency("fp "+this.name);this.ja[this.name]=null}};for(var p=a.files,r=0;r<p.length;++r)(new n(p[r].start,
p[r].end,p[r].audio)).open("GET",p[r].filename);A.addRunDependency("datafile_yaneuraou.data");A.ob||(A.ob={});A.ob["yaneuraou.data"]={dc:!1};u?(v(u),u=null):k=v}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof A.locateFilePackage||A.locateFile||(A.locateFile=A.locateFilePackage,B("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=A.locateFile?A.locateFile("yaneuraou.data",""):"yaneuraou.data",g=a.remote_package_size,k=null,u=A.getPreloadedPackage?A.getPreloadedPackage(f,g):null;u||b(f,g,function(n){k?(k(n),k=null):u=n},c);A.calledRun?d():(A.preRun||(A.preRun=[]),A.preRun.push(d))})({files:[{filename:"/eval/nn.bin",
start:0,end:893917,audio:0}],remote_package_size:893917,package_uuid:"0dd91f55-a3f0-450e-9909-60ff257bcba0"});
(function(){function a(){var g=d.shift();if(!b&&void 0!==g){if("quit"===g)return A.terminate();var k=A.ccall("usi_command","number",["string"],[g]);k&&d.unshift(g);f=k?2*f:1;setTimeout(a,f)}}var b=!1,c=[];A.print=function(g){0===c.length?console.log(g):setTimeout(function(){for(var k=0;k<c.length;k++)c[k](g)})};A.addMessageListener=function(g){c.push(g)};A.removeMessageListener=function(g){g=c.indexOf(g);0<=g&&c.splice(g,1)};A.terminate=function(){b=!0;D.qb()};var d=[],f=1;A.postMessage=function(g){d.push(g)};
A.postRun=function(){A.postMessage=function(g){d.push(g);1===d.length&&a()};a()}})();var ka={},E;for(E in A)A.hasOwnProperty(E)&&(ka[E]=A[E]);var la=[],ma="./this.program";function oa(a,b){throw b;}var pa=!1,F=!1,H=!1;pa="object"===typeof window;F="function"===typeof importScripts;H="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;var J=A.ENVIRONMENT_IS_PTHREAD||!1,K="";function qa(a){return A.locateFile?A.locateFile(a,K):K+a}var ra,sa,ta,ua;
if(H){K=F?require("path").dirname(K)+"/":__dirname+"/";ra=function(a,b){ta||(ta=require("fs"));ua||(ua=require("path"));a=ua.normalize(a);return ta.readFileSync(a,b?null:"utf8")};sa=function(a){a=ra(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(ma=process.argv[1].replace(/\\/g,"/"));la=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof va))throw a;});process.on("unhandledRejection",L);oa=function(a){process.exit(a)};A.inspect=
function(){return"[Emscripten Module object]"};var wa;try{wa=require("worker_threads")}catch(a){throw console.error('The "worker_threads" module is not supported in this node.js build - perhaps a newer version is needed?'),a;}global.Worker=wa.Worker}else if(pa||F)F?K=self.location.href:"undefined"!==typeof document&&document.currentScript&&(K=document.currentScript.src),_scriptDir&&(K=_scriptDir),0!==K.indexOf("blob:")?K=K.substr(0,K.lastIndexOf("/")+1):K="",H?(ra=function(a,b){ta||(ta=require("fs"));
ua||(ua=require("path"));a=ua.normalize(a);return ta.readFileSync(a,b?null:"utf8")},sa=function(a){a=ra(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a}):(ra=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},F&&(sa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}));H&&"undefined"===typeof performance&&(global.performance=require("perf_hooks").performance);
var xa=A.print||console.log.bind(console),B=A.printErr||console.warn.bind(console);for(E in ka)ka.hasOwnProperty(E)&&(A[E]=ka[E]);ka=null;A.arguments&&(la=A.arguments);A.thisProgram&&(ma=A.thisProgram);A.quit&&(oa=A.quit);var ya,za;A.wasmBinary&&(za=A.wasmBinary);var noExitRuntime=A.noExitRuntime||!0;"object"!==typeof WebAssembly&&L("no native wasm support detected");var l,Aa,Ba=!1;function assert(a,b){a||L("Assertion failed: "+b)}
function Ca(a){var b=A["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}function Da(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function M(a){return a?Da(ba(),a,void 0):""}function Ea(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var u=a.charCodeAt(++g);k=65536+((k&1023)<<10)|u&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function Fa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ga(a){var b=Fa(a)+1,c=Ha(b);Ea(a,e(),c,b);return c}function Ia(a,b){e().set(a,b)}var m,aa,ca,Ja,da,ea,ha;J&&(m=A.buffer);
function q(a){m=a;A.HEAP8=aa=new Int8Array(a);A.HEAP16=Ja=new Int16Array(a);A.HEAP32=da=new Int32Array(a);A.HEAPU8=ca=new Uint8Array(a);A.HEAPU16=new Uint16Array(a);A.HEAPU32=ea=new Uint32Array(a);A.HEAPF32=new Float32Array(a);A.HEAPF64=ha=new Float64Array(a)}var Ka=A.INITIAL_MEMORY||71303168;
if(J)l=A.wasmMemory,m=A.buffer;else if(A.wasmMemory)l=A.wasmMemory;else if(l=new WebAssembly.Memory({initial:Ka/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw B("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),H&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");l&&(m=l.buffer);Ka=m.byteLength;q(m);var La,Ma=[],Na=[],Oa=[],Pa=[];function Qa(){J||(A.noFSInit||Ra||(Ra=!0,Sa(),A.stdin=A.stdin,A.stdout=A.stdout,A.stderr=A.stderr,A.stdin?N("/dev","stdin",A.stdin):Ta("/dev/tty","/dev/stdin"),A.stdout?N("/dev","stdout",null,A.stdout):Ta("/dev/tty","/dev/stdout"),A.stderr?N("/dev","stderr",null,A.stderr):Ta("/dev/tty1","/dev/stderr"),Ua("/dev/stdin",0),Ua("/dev/stdout",1),Ua("/dev/stderr",1)),Va(Na))}
function Wa(){var a=A.preRun.shift();Ma.unshift(a)}var Xa=0,Ya=null,Za=null;function $a(){assert(!J,"addRunDependency cannot be used in a pthread worker");Xa++;A.monitorRunDependencies&&A.monitorRunDependencies(Xa)}function ab(){Xa--;A.monitorRunDependencies&&A.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}A.preloadedImages={};A.preloadedAudios={};
function L(a){if(A.onAbort)A.onAbort(a);J&&console.error("Pthread aborting at "+Error().stack);B(a);Ba=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ja(a);throw a;}function bb(){return O.startsWith("data:application/octet-stream;base64,")}var O="yaneuraou.wasm";bb()||(O=qa(O));function cb(){var a=O;try{if(a==O&&za)return new Uint8Array(za);if(sa)return sa(a);throw"both async and sync fetching of the wasm failed";}catch(b){L(b)}}
function db(){return za||!pa&&!F||"function"!==typeof fetch?Promise.resolve().then(function(){return cb()}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return cb()})}var eb,fb,hb={29300:function(){throw"Canceled!";},29318:function(a,b){setTimeout(function(){gb(a,b)},0)}};
function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(A);else{var c=b.ec;"number"===typeof c?void 0===b.Ba?La.get(c)():La.get(c)(b.Ba):c(void 0===b.Ba?null:b.Ba)}}}
function ib(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(y(),jb>>2),d=0;if(c==a&&Atomics.compareExchange(y(),jb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(y(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}A._emscripten_futex_wake=ib;
function kb(a){if(J)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=D.oa[a];b&&(y()[a+12>>2]=0,D.Ka(b.worker))}
var D={qa:[],ta:[],Xa:[],Ab:function(){for(var a=0;1>a;++a)D.Za()},Bb:function(){for(var a=P(228),b=0;57>b;++b)z()[a/4+b]=0;y()[a+12>>2]=a;b=a+152;y()[b>>2]=b;var c=P(512);for(b=0;128>b;++b)z()[c/4+b]=0;Atomics.store(z(),a+100>>2,c);Atomics.store(z(),a+40>>2,a);lb(a,!F,1);mb(a)},Cb:function(){D.receiveObjectTransfer=D.Ib;D.threadInit=D.Rb;D.threadCancel=D.Pb;D.threadExit=D.Qb;D.setExitStatus=D.Nb},oa:{},rb:[],Kb:function(){for(;0<D.rb.length;)D.rb.pop()();J&&Q()&&nb()},pb:function(a,b){Atomics.store(z(),
a+56>>2,1);Atomics.store(z(),a+60>>2,0);D.Kb();Atomics.store(z(),a+4>>2,b);Atomics.store(z(),a+0>>2,1);ib(a+0,2147483647);lb(0,0,0)},Nb:function(){},Qb:function(a){var b=Q();b&&(D.pb(b,a),J&&postMessage({cmd:"exit"}))},Pb:function(){D.pb(Q(),-1);postMessage({cmd:"cancelDone"})},qb:function(){for(var a in D.oa){var b=D.oa[a];b&&b.worker&&D.Ka(b.worker)}D.oa={};for(a=0;a<D.qa.length;++a){var c=D.qa[a];c.terminate()}D.qa=[];for(a=0;a<D.ta.length;++a)c=D.ta[a],b=c.ma,D.Sa(b),c.terminate();D.ta=[]},Sa:function(a){if(a){if(a.pa){var b=
y()[a.pa+100>>2];y()[a.pa+100>>2]=0;ob(b);ob(a.pa)}a.pa=0;a.Oa&&a.va&&ob(a.va);a.va=0;a.worker&&(a.worker.ma=null)}},Ka:function(a){D.Lb(function(){delete D.oa[a.ma.pa];D.qa.push(a);D.ta.splice(D.ta.indexOf(a),1);D.Sa(a.ma);a.ma=void 0})},Lb:function(a){y()[pb>>2]=0;try{a()}finally{y()[pb>>2]=1}},Ib:function(){},Rb:function(){for(var a in D.Xa)D.Xa[a]()},ib:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.ma&&(D.vb=a.ma.pa);if(d.targetThread&&d.targetThread!=Q()){var g=D.oa[d.pc];g?g.worker.postMessage(c.data,
d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)qb();else if("spawnThread"===f)rb(c.data);else if("cleanupThread"===f)kb(d.thread);else if("killThread"===f){c=d.thread;if(J)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";y()[c+12>>2]=0;c=D.oa[c];c.worker.terminate();
D.Sa(c);D.ta.splice(D.ta.indexOf(c.worker),1);c.worker.ma=void 0}else if("cancelThread"===f){c=d.thread;if(J)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";D.oa[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Da&&(a.Da(),delete a.Da);else if("print"===f)xa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)B("Thread "+d.threadId+": "+d.text);else if("alert"===
f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.ma&&Atomics.load(z(),a.ma.pa+64>>2)&&D.Ka(a);else if("exitProcess"===f)try{sb(d.returnCode)}catch(k){if(k instanceof va)return;throw k;}else"cancelDone"===f?D.Ka(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):B("worker sent an unknown command "+f));D.vb=void 0};a.onerror=function(c){B("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};H&&(a.on("message",function(c){a.onmessage({data:c})}),
a.on("error",function(c){a.onerror(c)}),a.on("exit",function(){}));a.postMessage({cmd:"load",urlOrBlob:A.mainScriptUrlOrBlob||_scriptDir,wasmMemory:l,wasmModule:Aa})},Za:function(){var a=qa("yaneuraou.worker.js");D.qa.push(new Worker(a))},yb:function(){0==D.qa.length&&(D.Za(),D.ib(D.qa[0]));return D.qa.pop()},$b:function(a){for(a=performance.now()+a;performance.now()<a;);}};A.establishStackSpace=function(a,b){tb(a,b);ub(a)};A.invokeEntryPoint=function(a,b){return La.get(a)(b)};var vb=0;
function wb(){return noExitRuntime||0<vb}A.keepRuntimeAlive=wb;var xb;xb=H?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:J?function(){return performance.now()-A.__performance_now_clock_drift}:function(){return performance.now()};function yb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function R(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=yb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function zb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ab(a){if("/"===a)return"/";a=R(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Bb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(H)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){L("randomDevice")}}
function Cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=yb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Db=[];function Eb(a,b){Db[a]={input:[],output:[],ya:b};Fb(a,Gb)}
var Gb={open:function(a){var b=Db[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ya.flush(a.tty)},flush:function(a){a.tty.ya.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ya.gb)throw new S(60);for(var f=0,g=0;g<d;g++){try{var k=a.tty.ya.gb(a.tty)}catch(u){throw new S(29);}if(void 0===k&&0===f)throw new S(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.ya.Va)throw new S(60);
try{for(var f=0;f<d;f++)a.tty.ya.Va(a.tty,b[c+f])}catch(g){throw new S(29);}d&&(a.node.timestamp=Date.now());return f}},Ib={gb:function(a){if(!a.input.length){var b=null;if(H){var c=Buffer.ja?Buffer.ja(256):new Buffer(256),d=0;try{d=ta.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Hb(b,!0)}return a.input.shift()},Va:function(a,b){null===b||10===b?(xa(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(xa(Da(a.output,0)),a.output=[])}},Jb={Va:function(a,b){null===b||10===b?(B(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(Da(a.output,0)),a.output=[])}},T={na:null,ra:function(){return T.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.na||(T.na={dir:{node:{sa:T.fa.sa,ka:T.fa.ka,lookup:T.fa.lookup,Ia:T.fa.Ia,rename:T.fa.rename,unlink:T.fa.unlink,rmdir:T.fa.rmdir,readdir:T.fa.readdir,symlink:T.fa.symlink},stream:{ua:T.ga.ua}},file:{node:{sa:T.fa.sa,ka:T.fa.ka},stream:{ua:T.ga.ua,read:T.ga.read,write:T.ga.write,Ya:T.ga.Ya,kb:T.ga.kb,mb:T.ga.mb}},link:{node:{sa:T.fa.sa,ka:T.fa.ka,readlink:T.fa.readlink},stream:{}},ab:{node:{sa:T.fa.sa,
ka:T.fa.ka},stream:Kb}});c=Lb(a,b,c,d);16384===(c.mode&61440)?(c.fa=T.na.dir.node,c.ga=T.na.dir.stream,c.ea={}):32768===(c.mode&61440)?(c.fa=T.na.file.node,c.ga=T.na.file.stream,c.ha=0,c.ea=null):40960===(c.mode&61440)?(c.fa=T.na.link.node,c.ga=T.na.link.stream):8192===(c.mode&61440)&&(c.fa=T.na.ab.node,c.ga=T.na.ab.stream);c.timestamp=Date.now();a&&(a.ea[b]=c,a.timestamp=c.timestamp);return c},fc:function(a){return a.ea?a.ea.subarray?a.ea.subarray(0,a.ha):new Uint8Array(a.ea):new Uint8Array(0)},
cb:function(a,b){var c=a.ea?a.ea.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ea,a.ea=new Uint8Array(b),0<a.ha&&a.ea.set(c.subarray(0,a.ha),0))},Jb:function(a,b){if(a.ha!=b)if(0==b)a.ea=null,a.ha=0;else{var c=a.ea;a.ea=new Uint8Array(b);c&&a.ea.set(c.subarray(0,Math.min(b,a.ha)));a.ha=b}},fa:{sa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ha:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.ub=4096;b.blocks=Math.ceil(b.size/b.ub);return b},ka:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.Jb(a,b.size)},lookup:function(){throw Mb[44];},Ia:function(a,b,c,d){return T.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Nb(b,
c)}catch(g){}if(d)for(var f in d.ea)throw new S(55);}delete a.parent.ea[a.name];a.parent.timestamp=Date.now();a.name=c;b.ea[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ea[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Nb(a,b),d;for(d in c.ea)throw new S(55);delete a.ea[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ea)a.ea.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},ga:{read:function(a,b,c,d,f){var g=a.node.ea;if(f>=a.node.ha)return 0;a=Math.min(a.node.ha-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===e().buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ea||a.ea.subarray)){if(g)return a.ea=b.subarray(c,c+d),a.ha=d;if(0===a.ha&&0===f)return a.ea=b.slice(c,c+d),a.ha=
d;if(f+d<=a.ha)return a.ea.set(b.subarray(c,c+d),f),d}T.cb(a,f+d);if(a.ea.subarray&&b.subarray)a.ea.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.ea[f+g]=b[c+g];a.ha=Math.max(a.ha,f+d);return d},ua:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ha);if(0>b)throw new S(28);return b},Ya:function(a,b,c){T.cb(a.node,b+c);a.node.ha=Math.max(a.node.ha,b+c)},kb:function(a,b,c,d,f,g){if(0!==b)throw new S(28);if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.ea;if(g&
2||a.buffer!==m){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=P(g);c<g;)e()[b+c++]=0;c=b;if(!c)throw new S(48);e().set(a,c)}else d=!1,c=a.byteOffset;return{nc:c,Yb:d}},mb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new S(43);if(f&2)return 0;T.ga.write(a,b,0,d,c,!1);return 0}}},Ob=null,Pb={},Qb=[],Rb=1,U=null,Sb=!0,V={},S=null,Mb={};
function W(a,b){a=Cb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={eb:!0,Wa:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Wa)throw new S(32);a=yb(a.split("/").filter(function(k){return!!k}),!1);var f=Ob;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=Nb(f,a[d]);c=R(c+"/"+a[d]);f.Ca&&(!g||g&&b.eb)&&(f=f.Ca.root);if(!g||b.Ra)for(g=0;40960===(f.mode&61440);)if(f=Tb(c),c=Cb(zb(c),f),f=W(c,{Wa:b.Wa}).node,40<g++)throw new S(32);}return{path:c,node:f}}
function Ub(a){for(var b;;){if(a===a.parent)return a=a.ra.lb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%U.length}function Nb(a,b){var c;if(c=(c=Wb(a,"x"))?c:a.fa.lookup?0:2)throw new S(c,a);for(c=U[Vb(a.id,b)];c;c=c.xa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.fa.lookup(a,b)}
function Lb(a,b,c,d){a=new Xb(a,b,c,d);b=Vb(a.parent.id,a.name);a.xa=U[b];return U[b]=a}var Yb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Wb(a,b){if(Sb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function $b(a,b){try{return Nb(a,b),20}catch(c){}return Wb(a,"wx")}
function ac(a){var b=4096;for(a=a||0;a<=b;a++)if(!Qb[a])return a;throw new S(33);}function bc(a,b){cc||(cc=function(){},cc.prototype={});var c=new cc,d;for(d in a)c[d]=a[d];a=c;b=ac(b);a.fd=b;return Qb[b]=a}var Kb={open:function(a){a.ga=Pb[a.node.rdev].ga;a.ga.open&&a.ga.open(a)},ua:function(){throw new S(70);}};function Fb(a,b){Pb[a]={ga:b}}
function dc(a,b){var c="/"===b,d=!b;if(c&&Ob)throw new S(10);if(!c&&!d){var f=W(b,{eb:!1});b=f.path;f=f.node;if(f.Ca)throw new S(10);if(16384!==(f.mode&61440))throw new S(54);}b={type:a,lc:{},lb:b,Hb:[]};a=a.ra(b);a.ra=b;b.root=a;c?Ob=a:f&&(f.Ca=b,f.ra&&f.ra.Hb.push(b))}function ec(a,b,c){var d=W(a,{parent:!0}).node;a=Ab(a);if(!a||"."===a||".."===a)throw new S(28);var f=$b(d,a);if(f)throw new S(f);if(!d.fa.Ia)throw new S(63);return d.fa.Ia(d,a,b,c)}function X(a){return ec(a,16895,0)}
function fc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return ec(a,b|8192,c)}function Ta(a,b){if(!Cb(a))throw new S(44);var c=W(b,{parent:!0}).node;if(!c)throw new S(44);b=Ab(b);var d=$b(c,b);if(d)throw new S(d);if(!c.fa.symlink)throw new S(63);c.fa.symlink(c,b,a)}
function gc(a){var b=W(a,{parent:!0}).node,c=Ab(a),d=Nb(b,c);a:{try{var f=Nb(b,c)}catch(k){f=k.la;break a}var g=Wb(b,"wx");f=g?g:16384===(f.mode&61440)?31:0}if(f)throw new S(f);if(!b.fa.unlink)throw new S(63);if(d.Ca)throw new S(10);try{V.willDeletePath&&V.willDeletePath(a)}catch(k){B("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.fa.unlink(b,c);b=Vb(d.parent.id,d.name);if(U[b]===d)U[b]=d.xa;else for(b=U[b];b;){if(b.xa===d){b.xa=d.xa;break}b=b.xa}try{if(V.onDeletePath)V.onDeletePath(a)}catch(k){B("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Tb(a){a=W(a).node;if(!a)throw new S(44);if(!a.fa.readlink)throw new S(28);return Cb(Ub(a.parent),a.fa.readlink(a))}function hc(a,b){a="string"===typeof a?W(a,{Ra:!0}).node:a;if(!a.fa.ka)throw new S(63);a.fa.ka(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ua(a,b,c,d){if(""===a)throw new S(44);if("string"===typeof b){var f=Yb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=R(a);try{g=W(a,{Ra:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new S(20);}else g=ec(a,c,0),f=!0;if(!g)throw new S(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new S(54);if(!f&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Zb(b)||b&512)?31:Wb(g,Zb(b)):44))throw new S(c);if(b&512){c=g;c="string"===typeof c?W(c,{Ra:!0}).node:c;if(!c.fa.ka)throw new S(63);if(16384===(c.mode&61440))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(f=Wb(c,"w"))throw new S(f);c.fa.ka(c,{size:0,timestamp:Date.now()})}b&=-131713;d=bc({node:g,path:Ub(g),flags:b,seekable:!0,position:0,ga:g.ga,Xb:[],error:!1},d);d.ga.open&&d.ga.open(d);!A.logReadFiles||b&1||(ic||(ic={}),a in ic||(ic[a]=1,B("FS.trackingDelegate error on read file: "+
a)));try{V.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),V.onOpenFile(a,g))}catch(k){B("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function jc(a){if(null===a.fd)throw new S(8);a.Ta&&(a.Ta=null);try{a.ga.close&&a.ga.close(a)}catch(b){throw b;}finally{Qb[a.fd]=null}a.fd=null}
function kc(a,b,c){if(null===a.fd)throw new S(8);if(!a.seekable||!a.ga.ua)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.ga.ua(a,b,c);a.Xb=[]}
function lc(a,b,c,d,f,g){if(0>d||0>f)throw new S(28);if(null===a.fd)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.ga.write)throw new S(28);a.seekable&&a.flags&1024&&kc(a,0,2);var k="undefined"!==typeof f;if(!k)f=a.position;else if(!a.seekable)throw new S(70);b=a.ga.write(a,b,c,d,f,g);k||(a.position+=b);try{if(a.path&&V.onWriteToFile)V.onWriteToFile(a.path)}catch(u){B("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
u.message)}return b}function Sa(){S||(S=function(a,b){this.node=b;this.Mb=function(c){this.la=c};this.Mb(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(function(a){Mb[a]=new S(a);Mb[a].stack="<generic error, no stack>"}))}var Ra;function mc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function nc(a,b){a="string"===typeof a?a:Ub(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=R(a+"/"+c);try{X(d)}catch(f){}a=d}}return d}
function oc(a,b,c,d){a=R(("string"===typeof a?a:Ub(a))+"/"+b);c=mc(c,d);return ec(a,(void 0!==c?c:438)&4095|32768,0)}function pc(a,b,c,d,f,g){a=b?R(("string"===typeof a?a:Ub(a))+"/"+b):a;d=mc(d,f);f=ec(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}hc(f,d|146);a=Ua(f,577);lc(a,c,0,c.length,0,g);jc(a);hc(f,d)}return f}
function N(a,b,c,d){a=R(("string"===typeof a?a:Ub(a))+"/"+b);b=mc(!!c,!!d);N.jb||(N.jb=64);var f=N.jb++<<8|0;Fb(f,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,u,n){for(var v=0,p=0;p<n;p++){try{var r=c()}catch(w){throw new S(29);}if(void 0===r&&0===v)throw new S(6);if(null===r||void 0===r)break;v++;k[u+p]=r}v&&(g.node.timestamp=Date.now());return v},write:function(g,k,u,n){for(var v=0;v<n;v++)try{d(k[u+v])}catch(p){throw new S(29);}n&&(g.node.timestamp=
Date.now());return v}});return fc(a,b,f)}function qc(a){if(!(a.Eb||a.Fb||a.link||a.ea)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ra)try{a.ea=Hb(ra(a.url),!0),a.ha=a.ea.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function rc(a,b,c,d,f){function g(){this.Ua=!1;this.ja=[]}g.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.hb(p/this.chunkSize|0)[r]}};g.prototype.Qa=function(p){this.hb=p};g.prototype.$a=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),w,h=(w=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;p=(w=p.getResponseHeader("Content-Encoding"))&&"gzip"===w;var t=1048576;h||(t=r);var x=this;x.Qa(function(C){var I=C*t,na=(C+1)*t-1;na=Math.min(na,r-1);if("undefined"===typeof x.ja[C]){var gd=x.ja;if(I>na)throw Error("invalid range ("+I+", "+na+") or no bytes requested!");if(na>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);r!==t&&G.setRequestHeader("Range","bytes="+I+"-"+na);"undefined"!=typeof Uint8Array&&(G.responseType=
"arraybuffer");G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);I=void 0!==G.response?new Uint8Array(G.response||[]):Hb(G.responseText||"",!0);gd[C]=I}if("undefined"===typeof x.ja[C])throw Error("doXHR failed!");return x.ja[C]});if(p||!r)t=r=1,t=r=this.hb(0).length,xa("LazyFiles on gzip forces download of the whole file when length is accessed");this.tb=
r;this.sb=t;this.Ua=!0};if("undefined"!==typeof XMLHttpRequest){if(!F)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.Ua||this.$a();return this.tb}},chunkSize:{get:function(){this.Ua||this.$a();return this.sb}}});var u=void 0}else u=c,k=void 0;var n=oc(a,b,d,f);k?n.ea=k:u&&(n.ea=null,n.url=u);Object.defineProperties(n,{ha:{get:function(){return this.ea.length}}});
var v={};Object.keys(n.ga).forEach(function(p){var r=n.ga[p];v[p]=function(){qc(n);return r.apply(null,arguments)}});v.read=function(p,r,w,h,t){qc(n);p=p.node.ea;if(t>=p.length)return 0;h=Math.min(p.length-t,h);if(p.slice)for(var x=0;x<h;x++)r[w+x]=p[t+x];else for(x=0;x<h;x++)r[w+x]=p.get(t+x);return h};n.ga=v;return n}
function sc(a,b,c,d,f,g,k,u,n,v){function p(h){function t(C){v&&v();u||pc(a,b,C,d,f,n);g&&g();ab(w)}var x=!1;A.preloadPlugins.forEach(function(C){!x&&C.canHandle(r)&&(C.handle(h,r,t,function(){k&&k();ab(w)}),x=!0)});x||t(h)}tc.ic();var r=b?Cb(R(a+"/"+b)):a,w="cp "+r;$a(w);"string"==typeof c?tc.Zb(c,function(h){p(h)},k):p(c)}var Y={},cc,ic,uc=void 0;function vc(){uc+=4;return y()[uc-4>>2]}function wc(a){a=Qb[a];if(!a)throw new S(8);return a}
function xc(a,b,c){if(J)return Z(2,1,a,b,c);uc=c;try{var d=wc(a);switch(b){case 0:var f=vc();return 0>f?-28:Ua(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=vc(),d.flags|=f,0;case 12:return f=vc(),l.buffer!=m&&q(l.buffer),Ja[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return y()[yc()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof Y&&g instanceof S||L(g),-g.la}}
function zc(a,b){if(J)return Z(3,1,a,b);try{if(0===b)return-28;if(b<Fa("/")+1)return-68;Ea("/",ba(),a,b);return a}catch(c){return"undefined"!==typeof Y&&c instanceof S||L(c),-c.la}}
function Ac(a,b,c){if(J)return Z(4,1,a,b,c);uc=c;try{var d=wc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=vc();return y()[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=vc();if(!d.ga.Db)throw new S(59);return d.ga.Db(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:L("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Y&&g instanceof
S||L(g),-g.la}}function Bc(a,b,c){if(J)return Z(5,1,a,b,c);uc=c;try{var d=M(a),f=c?vc():0;return Ua(d,b,f).fd}catch(g){return"undefined"!==typeof Y&&g instanceof S||L(g),-g.la}}var Cc=[];
function Dc(){H||F||(ya||(ya={}),ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(ya["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,B("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function Ec(a,b,c){if(0>=a||a>e().length||a&1)return-28;if(pa){if(Atomics.load(y(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(y(),jb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(y(),jb>>2,0),-73;d=Atomics.exchange(y(),jb>>2,0);if(0==d)break;qb();if(Atomics.load(y(),a>>2)!=b)return-6;Atomics.exchange(y(),jb>>2,a)}return 0}a=Atomics.wait(y(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Z(a,b){for(var c=arguments.length-2,d=Fc(),f=Ha(8*c),g=f>>3,k=0;k<c;k++){var u=arguments[2+k];fa()[g+k]=u}c=Gc(a,c,f,b);ub(d);return c}var Hc=[],Ic=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Jc(a){a=2<a?M(a):a;return Ic[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Kc(a,b,c){var d=Jc(a);if(!d)return-4;d.Ha&&(y()[d.Ha>>2]=b,y()[d.Ha+4>>2]=c);if(d.nb||!d.bc)d.nb&&(d=d.nb),a=!1,d.Ga&&d.Ga.Fa&&(a=d.Ga.Fa.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Ga.Fa.viewport(0,0,b,c);else{if(d.Ha){d=y()[d.Ha+8>>2];a=a?M(a):"";var f=Fc(),g=Ha(12),k=0;if(a){k=Fa(a)+1;var u=P(k);Ea(a,ba(),u,k);k=u}y()[g>>2]=k;y()[g+4>>2]=b;y()[g+8>>2]=c;Lc(0,d,657457152,0,k,g);ub(f);return 1}return-4}return 0}
function Mc(a,b,c){return J?Z(6,1,a,b,c):Kc(a,b,c)}function Nc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function Oc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Pc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Qc(a,b){a.fb||(a.fb=a.getContext,a.getContext=function(d,f){f=a.fb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?Rc(c,b):0}function Rc(a,b){var c=P(8);y()[c+4>>2]=Q();var d={hc:c,attributes:b,version:b.Gb,Fa:a};a.canvas&&(a.canvas.Ga=d);("undefined"===typeof b.bb||b.bb)&&Sc(d);return c}
function Sc(a){a||(a=Tc);if(!a.zb){a.zb=!0;var b=a.Fa;Nc(b);Oc(b);Pc(b);b.cc=b.getExtension("EXT_disjoint_timer_query");b.kc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Tc,Uc=["default","low-power","high-performance"],Vc={};
function Wc(){if(!Xc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ma||"./this.program"},b;for(b in Vc)a[b]=Vc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Xc=c}return Xc}var Xc;
function Yc(a,b){if(J)return Z(7,1,a,b);try{var c=0;Wc().forEach(function(d,f){var g=b+c;f=y()[a+4*f>>2]=g;for(g=0;g<d.length;++g)e()[f++>>0]=d.charCodeAt(g);e()[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Y&&d instanceof S||L(d),d.la}}function Zc(a,b){if(J)return Z(8,1,a,b);try{var c=Wc();y()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});y()[b>>2]=d;return 0}catch(f){return"undefined"!==typeof Y&&f instanceof S||L(f),f.la}}
function $c(a){if(J)return Z(9,1,a);try{var b=wc(a);jc(b);return 0}catch(c){return"undefined"!==typeof Y&&c instanceof S||L(c),c.la}}
function ad(a,b,c,d){if(J)return Z(10,1,a,b,c,d);try{a:{for(var f=wc(a),g=a=0;g<c;g++){var k=y()[b+8*g>>2],u=y()[b+(8*g+4)>>2],n=f,v=e(),p=k,r=u,w=void 0;if(0>r||0>w)throw new S(28);if(null===n.fd)throw new S(8);if(1===(n.flags&2097155))throw new S(8);if(16384===(n.node.mode&61440))throw new S(31);if(!n.ga.read)throw new S(28);var h="undefined"!==typeof w;if(!h)w=n.position;else if(!n.seekable)throw new S(70);var t=n.ga.read(n,v,p,r,w);h||(n.position+=t);var x=t;if(0>x){var C=-1;break a}a+=x;if(x<
u)break}C=a}y()[d>>2]=C;return 0}catch(I){return"undefined"!==typeof Y&&I instanceof S||L(I),I.la}}
function bd(a,b,c,d,f){if(J)return Z(11,1,a,b,c,d,f);try{var g=wc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;kc(g,a,d);fb=[g.position>>>0,(eb=g.position,1<=+Math.abs(eb)?0<eb?(Math.min(+Math.floor(eb/4294967296),4294967295)|0)>>>0:~~+Math.ceil((eb-+(~~eb>>>0))/4294967296)>>>0:0)];y()[f>>2]=fb[0];y()[f+4>>2]=fb[1];g.Ta&&0===a&&0===d&&(g.Ta=null);return 0}catch(k){return"undefined"!==typeof Y&&k instanceof S||L(k),k.la}}
function cd(a,b,c,d){if(J)return Z(12,1,a,b,c,d);try{a:{for(var f=wc(a),g=a=0;g<c;g++){var k=y()[b+8*g>>2],u=y()[b+(8*g+4)>>2],n=lc(f,e(),k,u,void 0);if(0>n){var v=-1;break a}a+=n}v=a}y()[d>>2]=v;return 0}catch(p){return"undefined"!==typeof Y&&p instanceof S||L(p),p.la}}
function rb(a){if(J)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=D.yb();if(!b)return 6;if(void 0!==b.ma)throw"Internal error!";if(!a.Ja)throw"Internal error, no pthread ptr!";D.ta.push(b);for(var c=P(512),d=0;128>d;++d)y()[c+4*d>>2]=0;var f=a.va+a.za;d=D.oa[a.Ja]={worker:b,va:a.va,za:a.za,Oa:a.Oa,pa:a.Ja};var g=d.pa>>2;Atomics.store(z(),g+16,a.detached);Atomics.store(z(),g+25,c);Atomics.store(z(),g+10,d.pa);Atomics.store(z(),g+20,a.za);Atomics.store(z(),
g+19,f);Atomics.store(z(),g+26,a.za);Atomics.store(z(),g+28,f);Atomics.store(z(),g+29,a.detached);c=dd()+40;Atomics.store(z(),g+43,c);b.ma=d;var k={cmd:"run",start_routine:a.Ob,arg:a.Ba,threadInfoStruct:a.Ja,stackBase:a.va,stackSize:a.za};b.Da=function(){k.time=performance.now();b.postMessage(k,a.Wb)};b.loaded&&(b.Da(),delete b.Da);return 0}
function ed(a,b){if(!a)return B("pthread_join attempted on a null thread pointer!"),71;if(J&&Q()==a)return B("PThread "+a+" is attempting to join to itself!"),16;if(!J&&fd()==a)return B("Main thread "+a+" is attempting to join to itself!"),16;if(y()[a+12>>2]!==a)return B("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(z(),a+64>>2))return B("Attempted to join thread "+a+", which was already detached!"),28;for(Dc();;){var c=
Atomics.load(z(),a+0>>2);if(1==c)return c=Atomics.load(z(),a+4>>2),b&&(y()[b>>2]=c),Atomics.store(z(),a+64>>2,1),J?postMessage({cmd:"cleanupThread",thread:a}):kb(a),0;if(J){var d=Q();if(d&&!Atomics.load(z(),d+56>>2)&&2==Atomics.load(z(),d+0>>2))throw"Canceled!";}J||qb();Ec(a+0,c,J?100:1)}}function hd(a){return 0===a%4&&(0!==a%100||0===a%400)}function id(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var jd=[31,29,31,30,31,30,31,31,30,31,30,31],kd=[31,28,31,30,31,30,31,31,30,31,30,31];
function ld(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(hd(a.getFullYear())?jd:kd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function md(a,b,c,d){function f(h,t,x){for(h="number"===typeof h?h.toString():h||"";h.length<t;)h=x[0]+h;return h}function g(h,t){return f(h,t,"0")}function k(h,t){function x(I){return 0>I?-1:0<I?1:0}var C;0===(C=x(h.getFullYear()-t.getFullYear()))&&0===(C=x(h.getMonth()-t.getMonth()))&&(C=x(h.getDate()-t.getDate()));return C}function u(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=ld(new Date(h.ia+1900,0,1),h.Na);var t=new Date(h.getFullYear()+1,0,4),x=u(new Date(h.getFullYear(),0,4));t=u(t);return 0>=k(x,h)?0>=k(t,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var v=y()[d+40>>2];d={Ub:y()[d>>2],Tb:y()[d+4>>2],La:y()[d+8>>2],Ea:y()[d+12>>2],Aa:y()[d+16>>2],ia:y()[d+20>>2],Ma:y()[d+24>>2],Na:y()[d+28>>2],qc:y()[d+
32>>2],Sb:y()[d+36>>2],Vb:v?M(v):""};c=M(c);v={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in v)c=c.replace(new RegExp(p,"g"),v[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");v={"%a":function(h){return r[h.Ma].substring(0,3)},"%A":function(h){return r[h.Ma]},"%b":function(h){return w[h.Aa].substring(0,3)},"%B":function(h){return w[h.Aa]},"%C":function(h){return g((h.ia+1900)/100|0,2)},"%d":function(h){return g(h.Ea,2)},"%e":function(h){return f(h.Ea,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.La,
2)},"%I":function(h){h=h.La;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Ea+id(hd(h.ia+1900)?jd:kd,h.Aa-1),3)},"%m":function(h){return g(h.Aa+1,2)},"%M":function(h){return g(h.Tb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.La&&12>h.La?"AM":"PM"},"%S":function(h){return g(h.Ub,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ma||7},"%U":function(h){var t=new Date(h.ia+1900,0,1),x=0===t.getDay()?t:ld(t,7-t.getDay());h=new Date(h.ia+1900,h.Aa,h.Ea);return 0>
k(x,h)?g(Math.ceil((31-x.getDate()+(id(hd(h.getFullYear())?jd:kd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(x,t)?"01":"00"},"%V":function(h){var t=new Date(h.ia+1901,0,4),x=u(new Date(h.ia+1900,0,4));t=u(t);var C=ld(new Date(h.ia+1900,0,1),h.Na);return 0>k(C,x)?"53":0>=k(t,C)?"01":g(Math.ceil((x.getFullYear()<h.ia+1900?h.Na+32-x.getDate():h.Na+1-x.getDate())/7),2)},"%w":function(h){return h.Ma},"%W":function(h){var t=new Date(h.ia,0,1),x=1===t.getDay()?t:ld(t,0===t.getDay()?1:7-t.getDay()+1);h=
new Date(h.ia+1900,h.Aa,h.Ea);return 0>k(x,h)?g(Math.ceil((31-x.getDate()+(id(hd(h.getFullYear())?jd:kd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(x,t)?"01":"00"},"%y":function(h){return(h.ia+1900).toString().substring(2)},"%Y":function(h){return h.ia+1900},"%z":function(h){h=h.Sb;var t=0<=h;h=Math.abs(h)/60;return(t?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Vb},"%%":function(){return"%"}};for(p in v)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),v[p](d)));p=Hb(c,
!1);if(p.length>b)return 0;Ia(p,a);return p.length-1}J||D.Ab();function Xb(a,b,c,d){a||(a=this);this.parent=a;this.ra=a.ra;this.Ca=null;this.id=Rb++;this.name=b;this.mode=c;this.fa={};this.ga={};this.rdev=d}
Object.defineProperties(Xb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Fb:{get:function(){return 16384===(this.mode&61440)}},Eb:{get:function(){return 8192===(this.mode&61440)}}});Sa();U=Array(4096);dc(T,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");Fb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});fc("/dev/null",259);Eb(1280,Ib);Eb(1536,Jb);fc("/dev/tty",1280);fc("/dev/tty1",1536);var a=Bb();N("/dev","random",a);N("/dev","urandom",a);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");dc({ra:function(){var b=Lb(a,"fd",16895,73);b.fa={lookup:function(c,d){var f=Qb[+d];if(!f)throw new S(8);c={parent:null,ra:{lb:"fake"},fa:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var tc;A.FS_createPath=nc;A.FS_createDataFile=pc;A.FS_createPreloadedFile=sc;A.FS_createLazyFile=rc;A.FS_createDevice=N;A.FS_unlink=gc;
var nd=[null,function(a,b){if(J)return Z(1,1,a,b)},xc,zc,Ac,Bc,Mc,Yc,Zc,$c,ad,bd,cd];function Hb(a,b){var c=Array(Fa(a)+1);a=Ea(a,c,0,c.length);b&&(c.length=a);return c}
var qd={c:function(a,b,c,d){L("Assertion failed: "+M(a)+", at: "+[b?M(b):"unknown filename",c,d?M(d):"unknown function"])},j:xc,G:zc,p:Ac,q:Bc,E:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(J)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=D.oa[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},b:function(){L()},F:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=xb();else return y()[yc()>>2]=28,-1;y()[b>>2]=a/
1E3|0;y()[b+4>>2]=a%1E3*1E6|0;return 0},m:function(a,b,c){Cc.length=0;var d;for(c>>=2;d=ba()[b++];)(d=105>d)&&c&1&&c++,Cc.push(d?fa()[c++>>1]:y()[c]),++c;return hb[a].apply(null,Cc)},z:Dc,g:function(){},e:Ec,f:ib,d:xb,t:function(a,b,c){ba().copyWithin(a,b,b+c)},A:function(a,b,c){Hc.length=b;c>>=3;for(var d=0;d<b;d++)Hc[d]=fa()[c+d];return(0>a?hb[-a-1]:nd[a]).apply(null,Hc)},u:function(a){var b=ba().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+
100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{l.grow(Math.min(2147483648,d)-m.byteLength+65535>>>16);q(l.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},B:function(a,b,c){return Jc(a)?Kc(a,b,c):Mc(a,b,c)},l:function(){},C:function(a,b){b>>=2;var c=y()[b+6];b={alpha:!!y()[b],depth:!!y()[b+1],stencil:!!y()[b+2],antialias:!!y()[b+3],premultipliedAlpha:!!y()[b+4],preserveDrawingBuffer:!!y()[b+5],powerPreference:Uc[c],failIfMajorPerformanceCaveat:!!y()[b+7],Gb:y()[b+
8],jc:y()[b+9],bb:y()[b+10],wb:y()[b+11],mc:y()[b+12],oc:y()[b+13]};a=Jc(a);return!a||b.wb?0:Qc(a,b)},x:Yc,y:Zc,D:function(a){sb(a)},i:$c,o:ad,r:bd,n:cd,s:function(){D.Bb()},a:l||A.wasmMemory,h:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return B("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return B("pthread_create called with a null thread pointer!"),28;var f=[];if(J&&0===f.length)return od(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=
b){var u=y()[b>>2];u+=81920;g=y()[b+8>>2];k=0!==y()[b+12>>2]}else u=2097152;(b=0==g)?g=pd(16,u):(g-=u,assert(0<g));for(var n=P(228),v=0;57>v;++v)z()[(n>>2)+v]=0;y()[a>>2]=n;y()[n+12>>2]=n;a=n+152;y()[a>>2]=a;c={va:g,za:u,Oa:b,detached:k,Ob:c,Ja:n,Ba:d,Wb:f};return J?(c.ac="spawnThread",postMessage(c,f),0):rb(c)},v:function(a,b){return ed(a,b)},w:function(a,b,c,d){return md(a,b,c,d)},k:function(a){var b=Date.now()/1E3|0;a&&(y()[a>>2]=b);return b}};
(function(){function a(f,g){A.asm=f.exports;La=A.asm.J;Na.unshift(A.asm.H);D.Xa.push(A.asm.N);Aa=g;if(!J){var k=D.qa.length;D.qa.forEach(function(u){D.ib(u,function(){--k||ab("wasm-instantiate")})})}}function b(f){a(f.instance,f.module)}function c(f){return db().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){B("failed to asynchronously prepare wasm: "+g);L(g)})}var d={a:qd};J||$a("wasm-instantiate");if(A.instantiateWasm)try{return A.instantiateWasm(d,a)}catch(f){return B("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return za||"function"!==typeof WebAssembly.instantiateStreaming||bb()||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){B("wasm streaming compile failed: "+g);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ja);return{}})();A.___wasm_call_ctors=function(){return(A.___wasm_call_ctors=A.asm.H).apply(null,arguments)};
A._main=function(){return(A._main=A.asm.I).apply(null,arguments)};var P=A._malloc=function(){return(P=A._malloc=A.asm.K).apply(null,arguments)},ob=A._free=function(){return(ob=A._free=A.asm.L).apply(null,arguments)};A._usi_command=function(){return(A._usi_command=A.asm.M).apply(null,arguments)};A._emscripten_tls_init=function(){return(A._emscripten_tls_init=A.asm.N).apply(null,arguments)};
var yc=A.___errno_location=function(){return(yc=A.___errno_location=A.asm.O).apply(null,arguments)},dd=A._emscripten_get_global_libc=function(){return(dd=A._emscripten_get_global_libc=A.asm.P).apply(null,arguments)},Q=A._pthread_self=function(){return(Q=A._pthread_self=A.asm.Q).apply(null,arguments)},nb=A.___pthread_tsd_run_dtors=function(){return(nb=A.___pthread_tsd_run_dtors=A.asm.R).apply(null,arguments)};
A._emscripten_current_thread_process_queued_calls=function(){return(A._emscripten_current_thread_process_queued_calls=A.asm.S).apply(null,arguments)};
var mb=A._emscripten_register_main_browser_thread_id=function(){return(mb=A._emscripten_register_main_browser_thread_id=A.asm.T).apply(null,arguments)},fd=A._emscripten_main_browser_thread_id=function(){return(fd=A._emscripten_main_browser_thread_id=A.asm.U).apply(null,arguments)},gb=A.__emscripten_do_dispatch_to_thread=function(){return(gb=A.__emscripten_do_dispatch_to_thread=A.asm.V).apply(null,arguments)},od=A._emscripten_sync_run_in_main_thread_4=function(){return(od=A._emscripten_sync_run_in_main_thread_4=
A.asm.W).apply(null,arguments)},qb=A._emscripten_main_thread_process_queued_calls=function(){return(qb=A._emscripten_main_thread_process_queued_calls=A.asm.X).apply(null,arguments)},Gc=A._emscripten_run_in_main_runtime_thread_js=function(){return(Gc=A._emscripten_run_in_main_runtime_thread_js=A.asm.Y).apply(null,arguments)},Lc=A.__emscripten_call_on_thread=function(){return(Lc=A.__emscripten_call_on_thread=A.asm.Z).apply(null,arguments)},lb=A.__emscripten_thread_init=function(){return(lb=A.__emscripten_thread_init=
A.asm._).apply(null,arguments)},Fc=A.stackSave=function(){return(Fc=A.stackSave=A.asm.$).apply(null,arguments)},ub=A.stackRestore=function(){return(ub=A.stackRestore=A.asm.aa).apply(null,arguments)},Ha=A.stackAlloc=function(){return(Ha=A.stackAlloc=A.asm.ba).apply(null,arguments)},tb=A._emscripten_stack_set_limits=function(){return(tb=A._emscripten_stack_set_limits=A.asm.ca).apply(null,arguments)},pd=A._memalign=function(){return(pd=A._memalign=A.asm.da).apply(null,arguments)},pb=A.__emscripten_allow_main_runtime_queued_calls=
29288,jb=A.__emscripten_main_thread_futex=8761268;A.ccall=function(a,b,c,d){var f={string:function(v){var p=0;if(null!==v&&void 0!==v&&0!==v){var r=(v.length<<2)+1,w=p=Ha(r);Ea(v,ba(),w,r)}return p},array:function(v){var p=Ha(v.length);Ia(v,p);return p}},g=Ca(a),k=[];a=0;if(d)for(var u=0;u<d.length;u++){var n=f[c[u]];n?(0===a&&(a=Fc()),k[u]=n(d[u])):k[u]=d[u]}c=g.apply(null,k);c=function(v){return"string"===b?M(v):"boolean"===b?!!v:v}(c);0!==a&&ub(a);return c};A.addRunDependency=$a;
A.removeRunDependency=ab;A.FS_createPath=nc;A.FS_createDataFile=pc;A.FS_createPreloadedFile=sc;A.FS_createLazyFile=rc;A.FS_createDevice=N;A.FS_unlink=gc;A.PThread=D;A.PThread=D;A.wasmMemory=l;A.ExitStatus=va;var rd;function va(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Za=function sd(){rd||td();rd||(Za=sd)};
function td(a){function b(){if(!rd&&(rd=!0,A.calledRun=!0,!Ba)){Qa();J||(Sb=!1,Va(Oa));ia(A);if(A.onRuntimeInitialized)A.onRuntimeInitialized();if(ud){var c=a,d=A._main;c=c||[];var f=c.length+1,g=Ha(4*(f+1));y()[g>>2]=Ga(ma);for(var k=1;k<f;k++)y()[(g>>2)+k]=Ga(c[k-1]);y()[(g>>2)+f]=0;try{var u=d(f,g);sb(u,!0)}catch(n){n instanceof va||"unwind"==n||((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),B("exception thrown: "+c),oa(1,n))}finally{}}if(!J){if(A.postRun)for("function"==typeof A.postRun&&
(A.postRun=[A.postRun]);A.postRun.length;)c=A.postRun.shift(),Pa.unshift(c);Va(Pa)}}}a=a||la;if(!(0<Xa))if(J)ia(A),Qa(),postMessage({cmd:"loaded"});else{if(!J){if(A.preRun)for("function"==typeof A.preRun&&(A.preRun=[A.preRun]);A.preRun.length;)Wa();Va(Ma)}0<Xa||(A.setStatus?(A.setStatus("Running..."),setTimeout(function(){setTimeout(function(){A.setStatus("")},1);b()},1)):b())}}A.run=td;
function sb(a,b){if(!b||!wb()||0!==a){if(!b&&J)throw postMessage({cmd:"exitProcess",returnCode:a}),new va(a);if(!wb()){D.qb();if(A.onExit)A.onExit(a);Ba=!0}oa(a,new va(a))}}if(A.preInit)for("function"==typeof A.preInit&&(A.preInit=[A.preInit]);0<A.preInit.length;)A.preInit.pop()();var ud=!0;A.noInitialRun&&(ud=!1);J&&(noExitRuntime=!1,D.Cb());td();


  return YaneuraOu.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = YaneuraOu;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return YaneuraOu; });
else if (typeof exports === 'object')
  exports["YaneuraOu"] = YaneuraOu;
